run_name: 'ftn_no_rotate'
gpu: 'cpu'
batch_size: 32
lr: 0.001
repr_dims: 320
epochs: 200
seed: 42
max_threads: 8
freq: 128
seg_length_sec: 10
cv_num: 5
data_folder: '/work/pi_sunghoonlee_umass_edu/Juhyeon/FNT_data'
